name: quote_repository
publish_to: none

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  equatable: ^2.0.5
  fav_qs_api:
    path: ../fav_qs_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  meta: ^1.12.0

dev_dependencies:
  test: ^1.25.2
  lints: ^4.0.0
  mocktail: ^1.0.4
