name: monitoring
publish_to: none

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.3.0
  #firebase_auth: ^3.4.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_dynamic_links: ^6.0.5 #has been discontinued
  firebase_dynamic_links_platform_interface: ^0.2.3+13
  firebase_remote_config: ^5.1.0
  #firebase_auth_web: ^3.3.18

dev_dependencies:
  test: ^1.25.2
  lints: ^4.0.0

dependency_overrides:
  firebase_core_platform_interface: ^4.4.1
