name: key_value_storage
publish_to: none

environment:
  sdk: ">=3.4.0-190.1.beta <4.0.0"

dependencies:
  hive: ^2.2.3
  meta: ^1.12.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  lints: ^4.0.0
  test: ^1.25.2
