name: quote_list
publish_to: none

environment: 
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  component_library:
    path: ../../component_library
  quote_repository:
    path: ../../quote_repository
  user_repository:
    path: ../../user_repository
  domain_models:
    path: ../../domain_models
  monitoring:
    path: ../../monitoring
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.2
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true