name: fav_qs_api
publish_to: none

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  build_runner: ^2.4.9
  dio: ^5.7.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0  
  meta: ^1.12.0

dev_dependencies:
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.7