name: component_library
publish_to: none

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_localizations: #internationalization support
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  storybook_flutter_test: ^0.1.0+2
  test: ^1.25.2


flutter:
  generate: true
  assets:
    - assets
  fonts:
    - family: Fondamento
      fonts:
        - asset: assets/fondamento/Fondamento-Regular.ttf
        - asset: assets/fondamento/Fondamento-Italic.ttf